Changed init script to default template
Rolling restarts are not necessary for us anyway

diff --git a/config/deployment/unicorn b/config/deployment/unicorn
--- a/config/deployment/unicorn
+++ b/config/deployment/unicorn
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 ### BEGIN INIT INFO
 # Provides:          unicorn
@@ -41,7 +41,7 @@ case $1 in
   start)
     sig 0 && echo >&2 "Already running" && exit 0
     echo "Starting $APP_NAME"
-    eval $CMD
+    su - $USER -c "$CMD"
     ;;
   stop)
     echo "Stopping $APP_NAME"
@@ -53,35 +53,14 @@ case $1 in
     sig TERM && exit 0
     echo >&2 "Not running"
     ;;
-  restart)
-    sig QUIT && echo "Restarting $DESC" && sleep 2 \
-      && su - $USER -c "$CMD" && exit 0
-    echo >&2 "Couldn't restart."
+  restart|reload|upgrade)
+    sig USR2 && echo "reloaded $APP_NAME" && exit 0
+    echo >&2 "Couldn't reload, starting '$CMD' instead"
+    $CMD
     ;;
-  reload|upgrade)
-    if sig USR2 && echo "Upgrading $APP_NAME" && sleep 10 \
-      && sig 0 && oldsig QUIT
-    then
-      n=$TIMEOUT
-      while test -s $old_pid && test $n -ge 0
-      do
-        printf '.' && sleep 1 && n=$(( $n - 1 ))
-      done
-      echo
-
-      if test $n -lt  0 && test -s $old_pid
-      then
-        echo >&2 "$old_pid still exists after $TIMEOUT seconds"
-        exit 1
-      fi
-      exit 0
-    fi
-    echo >&2 "Couldn't upgrade, starting 'su - $USER -c \"$CMD\"' instead"
-    su - $USER -c "$CMD"
-    ;;
-  status)
-    sig 0 && echo >&2 "$APP_NAME is running." && exit 0
-    echo >&2 "$APP_NAME is not running."
+  rotate)
+    sig USR1 && echo rotated logs OK && exit 0
+    echo >&2 "Couldn't rotate logs" && exit 1
     ;;
   *)
     echo >&2 $USAGE
